from typing import Final

import numpy as np
import numpy.typing as npt

KERNEL_SCHEMA_VERSION: Final[int]
OBSERVATION_SCHEMA_VERSION: Final[int]
RULESET_ID: Final[str]
ACTION_COUNT: Final[int]
HAND_SLOTS: Final[int]

class FixedAttackBatch:
    def __init__(
        self,
        batch_size: int,
        token_ids: npt.NDArray[np.uint32],
        attack_values: npt.NDArray[np.uint16],
        seed: int = ...,
        initial_hp: int = ...,
    ) -> None: ...
    @property
    def batch_size(self) -> int: ...
    @property
    def seed(self) -> int: ...
    @property
    def initial_hp(self) -> int: ...
    @property
    def global_features(self) -> npt.NDArray[np.float32]: ...
    @property
    def player_features(self) -> npt.NDArray[np.float32]: ...
    @property
    def player_mask(self) -> npt.NDArray[np.bool_]: ...
    @property
    def hand_token_ids(self) -> npt.NDArray[np.int64]: ...
    @property
    def hand_mask(self) -> npt.NDArray[np.bool_]: ...
    @property
    def action_mask(self) -> npt.NDArray[np.bool_]: ...
    @property
    def active_players(self) -> npt.NDArray[np.uint8]: ...
    @property
    def terminal_returns(self) -> npt.NDArray[np.float32]: ...
    @property
    def terminated(self) -> npt.NDArray[np.bool_]: ...
    @property
    def episode_ids(self) -> npt.NDArray[np.uint64]: ...
    @property
    def turn_numbers(self) -> npt.NDArray[np.uint16]: ...
    def reset(self) -> None: ...
    def reset_done(self) -> int: ...
    def step(self, actions: npt.NDArray[np.int64]) -> None: ...
